name: "QA Automation Testing"

on:
  push:
    branches:
      - github_actions_yml
  pull_request:
    branches:
      - main

jobs:
    backend-regression-tests:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.13'

        - name: Install dependencies via requirements.txt
          run: pip install -r requirements.txt

        - name: Run Backend tests
          env:
            WOO_KEY: ${{ secrets.WOO_KEY }}
            WOO_SECRET: ${{ secrets.WOO_SECRET }}
            DB_USER: ${{ secrets.DB_USER }}
            DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
            PYTHONPATH: "${{ github.workspace }}"

          run: |
            echo "Setting up environment variables"
            source variables_local.env
            cd demostore_automation
            pytest tests/backend -v -s --html=reports/backend-regression.html
            echo "Successfully ran backend tests"

    frontend-regression-tests-chrome:
      runs-on: ubuntu-latest
      services:
        chrome:
          image: selenium/standalone-chrome:latest
          ports:
            - 4444:4444
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.13'

        - name: Install dependencies
          run: pip install -r requirements.txt

        - name: Run frontend tests on Chrome
          env:
            WOO_KEY: ${{ secrets.WOO_KEY }}
            WOO_SECRET: ${{ secrets.WOO_SECRET }}
            PYTHONPATH: "${{ github.workspace }}"
            BROWSER: remote_chrome
            REMOTE_WEBDRIVER: http://localhost:4444
          run: |
            echo "Running frontend tests on Chrome..."
            source variables_local.env
            cd demostore_automation
            pytest tests/frontend -v -s --html=reports/frontend-regression-chrome.html
